### ISSUE TITLE
Goal for Week 2 & 3 Defined

### ISSUE THREAD

**Issue by ladydanger** [team-melbourne-rgsoc2015/Roadmap#1]
Hi @eviltrout

We were looking through doubleclick for publishers and wanted to know if the slightly changed scope of our goal for week 2-3 is ok with you:

GOAL: Creating a very basic DFP plugin with 1 ad block using the dummy code (see below) in the header as a ship item hopefully due by the end of the 3rd week.

Reason - The reason we've done this is because we think it may be achievable within 2 weeks and we're also having issues being able to test the functionality of adsense and DFP locally, whereas with the dummy code we can push it through.  

We've also put up a roadmap repo...

```
  <!-- This is the GPT library that loads from http(s)://www.googletagservices.com/tag/js/gpt.js. -->
<script type="text/javascript">
      var googletag = googletag || {};
      googletag.cmd = googletag.cmd || [];
      (function() {
        var gads = document.createElement("script");
        gads.async = true;
        gads.type = "text/javascript";
        var useSSL = "https:" == document.location.protocol;
        gads.src = (useSSL ? "https:" : "http:") + "//www.googletagservices.com/tag/js/gpt.js";
        var node =document.getElementsByTagName("script")[0];
        node.parentNode.insertBefore(gads, node);
       })();
    </script>
    <!-- The GPT library ends -->
    <!-- Define slot and initiate GPT using enableServices method in the 
    googletag class -->
  <script type="text/javascript">
    googletag.cmd.push(function() {
      var adSlot1 = googletag.defineSlot('/6355419/Travel/Europe/France/Paris',[300, 250], "banner1");
      adSlot1.addService(googletag.pubads());
      googletag.enableServices();
    });
  </script>
  <!-- ends of this script -->
```

Let us know what you think...

**Comment by eviltrout** [comment]
Sure that seems quite reasonable!

What issues are you having testing it locally?

**Comment by ladydanger** [comment]
Thanks Robin, we'll do that... hopefully we'll get it done by the 3rd week.  With the local testing stuff, it's mainly with adsense b/c ads and their policies.  We can't find test code that we could use whereas with DFP they have a dummy tag that loads which makes it easier for us n00bs to see if something's working or not.
