### ISSUE TITLE
Adsense Reload

### ISSUE THREAD

**Issue by ladydanger** [team-melbourne-rgsoc2015/Roadmap#2]
Hi @snjqi188,

Did you want to chat about this on Monday or anytime this week - not urgent... but interesting nonetheless... I think it would be fun and interesting to see/test out whether the adsense plugin that currently exists (as it is a modification to the adsense code), affects ad impressions with their reload code.  
Adsense: Our program policies do not permit any alteration to AdSense code which artificially inflates ad performance or harms advertiser conversions.

Here's a site using the adsense plugin http://ozim.co.il/

**Comment by cyberkoi** [comment]
Is it possible to test it with dummy code?

**Comment by ladydanger** [comment]
oh yeah... I've been using the breaks in the inpect manager, but will try this live b/c it'd be easier to see the impressions.
